# Generated by Django 5.0.6 on 2024-06-11 12:22

import django.db.models.deletion
import wine_vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, validators=[wine_vault.models.starts_with_letter_validator])),
                ('region', models.CharField(max_length=50, validators=[wine_vault.models.starts_with_letter_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reviews', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[wine_vault.models.starts_with_letter_validator])),
            ],
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[wine_vault.models.starts_with_letter_validator])),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to=wine_vault.models.upload_to)),
                ('image_url', models.URLField(null=True)),
                ('vintage', models.PositiveIntegerField(max_length=4, null=True)),
                ('price', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.location')),
                ('preferences', models.ManyToManyField(related_name='wine_preferences', to='wine_vault.preferences')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.rating')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.winery')),
                ('wine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.winetype')),
            ],
        ),
    ]
