# Generated by Django 5.0.6 on 2024-06-04 09:35

import django.core.validators
import django.db.models.deletion
import wine_vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reviews', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='name for wine is too long max 100')])),
            ],
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to=wine_vault.models.upload_to)),
                ('image_url', models.URLField(null=True)),
                ('vintage', models.PositiveIntegerField(max_length=4, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.location')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.rating')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.winery')),
                ('wine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_vault.winetype')),
            ],
        ),
    ]
