# Generated by Django 5.0.6 on 2024-06-02 10:29

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_upload',
            field=models.ImageField(default=1, upload_to=pathlib.PurePosixPath('upload/wine')),
            preserve_default=False,
        ),
    ]
