# Generated by Django 5.0.6 on 2024-06-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='year_of_release',
            new_name='vintage',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='description',
        ),
    ]
