# Generated by Django 5.0.6 on 2024-06-03 22:14

import wine_vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to=wine_vault.models.upload_to),
        ),
    ]
