# Generated by Django 5.0.6 on 2024-06-15 16:16

import wine_vault.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine_vault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="name",
            field=models.CharField(
                max_length=30, validators=[wine_vault.validators.validate_wine_name]
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="vintage",
            field=models.PositiveIntegerField(
                max_length=4,
                null=True,
                validators=[wine_vault.validators.validate_wine_vintage],
            ),
        ),
    ]
