# Generated by Django 5.0.6 on 2024-06-03 21:38

import wine_vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_vault', '0002_wine_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image_upload',
            field=models.ImageField(upload_to=wine_vault.models.upload_to),
        ),
    ]
