# Generated by Django 5.0.6 on 2024-06-15 16:16

import wine_user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wineuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[wine_user.validators.email_validate],
                verbose_name="email address",
            ),
        ),
    ]
